/**
 * Brick Breaker — Campaign Level Pack (30 Levels)
 *
 * Grid: 13 cols × 10 rows per level.
 * Legend: . empty, N normal(1hp), H hard(2hp), V heavy(3hp),
 *         S steel(unbreakable), E explosive, P power, M moving.
 *
 * Rows are parsed left-to-right, top-to-bottom. Rows shorter than 13
 * are right-padded with '.'; rows longer are truncated.
 *
 * @module gamesV4/games/brickBreaker/levels
 */

import type { LevelDef } from "./types";

export const LEVEL_PACK: LevelDef[] = [
  {
    id: 1,
    name: "Warm-Up",
    ballSpeed: 1.0,
    paddle: 1.0,
    powerRate: 0.16,
    rows: [
      ".............",
      "..NNNNNNNNN..",
      "...NNNNNNN...",
      "....NNNNN....",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 2,
    name: "Staircase",
    ballSpeed: 1.0,
    paddle: 1.0,
    powerRate: 0.16,
    rows: [
      "N............",
      ".N...........",
      "..N..........",
      "...N.........",
      "....N........",
      ".....N.......",
      "......N......",
      ".......N.....",
      "........N....",
      ".........N...",
    ],
  },
  {
    id: 3,
    name: "Smile",
    ballSpeed: 1.02,
    paddle: 1.0,
    powerRate: 0.15,
    rows: [
      "..NN.....NN..",
      "..NN.....NN..",
      ".............",
      "N...N...N...N",
      "N...........N",
      "N..N.....N..N",
      "N...NNNNN...N",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 4,
    name: "Double Bars",
    ballSpeed: 1.03,
    paddle: 1.0,
    powerRate: 0.15,
    rows: [
      "NNNNNNNNNNNNN",
      ".............",
      "NNNNNNNNNNNNN",
      ".............",
      "NNNNNNNNNNNNN",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 5,
    name: "Pocket Gaps",
    ballSpeed: 1.05,
    paddle: 1.0,
    powerRate: 0.14,
    rows: [
      "NNN.NNN.NNN.N",
      "NNN.NNN.NNN.N",
      "NNN.NNN.NNN.N",
      ".............",
      "....NNNNN....",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 6,
    name: "First Armor",
    ballSpeed: 1.07,
    paddle: 0.98,
    powerRate: 0.14,
    rows: [
      "HHHHHHHHHHHHH",
      "NNNNNNNNNNNNN",
      ".............",
      "....NNNNN....",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 7,
    name: "Checker Lite",
    ballSpeed: 1.08,
    paddle: 0.98,
    powerRate: 0.14,
    rows: [
      "N.N.N.N.N.N.N",
      ".N.N.N.N.N.N.",
      "N.N.N.N.N.N.N",
      ".N.N.N.N.N.N.",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 8,
    name: "Diamond",
    ballSpeed: 1.1,
    paddle: 0.98,
    powerRate: 0.13,
    rows: [
      ".....N.N.....",
      "....NHHHN....",
      "...NHVVVHN...",
      "..NHVVVVVHN..",
      "...NHVVVHN...",
      "....NHHHN....",
      ".....N.N.....",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 9,
    name: "Thin Channel",
    ballSpeed: 1.12,
    paddle: 0.96,
    powerRate: 0.13,
    rows: [
      "SSSSS...SSSSS",
      "NNNNN...NNNNN",
      "HHHHH...HHHHH",
      "NNNNN...NNNNN",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 10,
    name: "Armor Rows",
    ballSpeed: 1.15,
    paddle: 0.96,
    powerRate: 0.13,
    rows: [
      "HHHHHHHHHHHHH",
      "HHHHHHHHHHHHH",
      "NNNNNNNNNNNNN",
      "NNNNNNNNNNNNN",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 11,
    name: "Steel Posts",
    ballSpeed: 1.18,
    paddle: 0.95,
    powerRate: 0.12,
    rows: [
      "S...NNNNN...S",
      "S...NNNNN...S",
      "S...HHHHH...S",
      "S...NNNNN...S",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 12,
    name: "Power Lane",
    ballSpeed: 1.2,
    paddle: 0.95,
    powerRate: 0.12,
    rows: [
      "NNNNPPPPNNNNN",
      "NNNN....NNNNN",
      "HHHH....HHHHH",
      "NNNNPPPPNNNNN",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 13,
    name: "Heavy Core",
    ballSpeed: 1.22,
    paddle: 0.94,
    powerRate: 0.12,
    rows: [
      "NNNNNNNNNNNNN",
      "NNNHHHHHHHNNN",
      "NNHHVVVVVHHNN",
      "NNNHHHHHHHNNN",
      "NNNNNNNNNNNNN",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 14,
    name: "Split Walls",
    ballSpeed: 1.24,
    paddle: 0.94,
    powerRate: 0.11,
    rows: [
      "SSSSS...SSSSS",
      "NNNNN...NNNNN",
      "HHHHH...HHHHH",
      "NNNNN...NNNNN",
      "SSSSS...SSSSS",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 15,
    name: "Explosive Intro",
    ballSpeed: 1.26,
    paddle: 0.92,
    powerRate: 0.11,
    rows: [
      "NNNNEEEEENNNN",
      "NNNNNHHHNNNNN",
      "NNNN.....NNNN",
      "HHHH.....HHHH",
      "NNNNPPPPNNNNN",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 16,
    name: "Blast Pockets",
    ballSpeed: 1.3,
    paddle: 0.9,
    powerRate: 0.11,
    rows: [
      "S..E..NNN..ES",
      "..NNNHHHHHNN.",
      "..NN.HVVVH.NN",
      "..NNNHHHHHNN.",
      "S..E..NNN..ES",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 17,
    name: "Steel Maze I",
    ballSpeed: 1.32,
    paddle: 0.9,
    powerRate: 0.1,
    rows: [
      "SSSSSSSSSSSSS",
      "SNNN...NNNNS.",
      "S.HH...HHHS..",
      "SNNN...NNNNS.",
      "SSSS...SSSSS.",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 18,
    name: "Ring",
    ballSpeed: 1.34,
    paddle: 0.88,
    powerRate: 0.1,
    rows: [
      "..NNNNNNNNN..",
      ".NHHHHHHHHHN.",
      "NHH.......HHN",
      "NH..VVVVV..HN",
      "NH..VVVVV..HN",
      "NHH.......HHN",
      ".NHHHHHHHHHN.",
      "..NNNNNNNNN..",
      ".............",
      ".............",
    ],
  },
  {
    id: 19,
    name: "Heavy Rain",
    ballSpeed: 1.36,
    paddle: 0.88,
    powerRate: 0.1,
    rows: [
      "V.V.V.V.V.V.V",
      ".V.V.V.V.V.V.",
      "V.V.V.V.V.V.V",
      ".V.V.V.V.V.V.",
      "HHHHHHHHHHHHH",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 20,
    name: "Steel Maze II",
    ballSpeed: 1.4,
    paddle: 0.85,
    powerRate: 0.1,
    rows: [
      "SSSSSSSSSSSSS",
      "SNNN.SSS.NNNS",
      "SHHH.SSS.HHHS",
      "SNNN.SSS.NNNS",
      "SSSS.SSS.SSSS",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 21,
    name: "Moving Intro",
    ballSpeed: 1.44,
    paddle: 0.84,
    powerRate: 0.09,
    rows: [
      "MMMMM...MMMMM",
      "NNNNN...NNNNN",
      "HHHHH...HHHHH",
      "NNNNNPPPPNNNN",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 22,
    name: "Crossfire",
    ballSpeed: 1.46,
    paddle: 0.83,
    powerRate: 0.09,
    rows: [
      "..E...MMM...E",
      ".NNN.HHHHH.NN",
      "..E...MMM...E",
      ".....VVVVV...",
      "..P.........P",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 23,
    name: "Moving Rails",
    ballSpeed: 1.48,
    paddle: 0.82,
    powerRate: 0.09,
    rows: [
      "SSSSSMMMSSSMM",
      "NNNNN...NNNNN",
      "HHHHH...HHHHH",
      "NNNNN...NNNNN",
      "SSSSSMMMSSSMM",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 24,
    name: "Tight Diamond",
    ballSpeed: 1.5,
    paddle: 0.8,
    powerRate: 0.08,
    rows: [
      ".....H.H.....",
      "....HVVVH....",
      "...HVSSSVH...",
      "..HVSSSSSVH..",
      "...HVSSSVH...",
      "....HVVVH....",
      ".....H.H.....",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 25,
    name: "Explode & Move",
    ballSpeed: 1.52,
    paddle: 0.8,
    powerRate: 0.08,
    rows: [
      "MMEEMMEEEММЕE",
      "NNNNHHHHNNNNN",
      "....P...P....",
      "HHHHVVVVHHHHH",
      "NNNNHHHHNNNNN",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 26,
    name: "Boss Plate I",
    ballSpeed: 1.56,
    paddle: 0.78,
    powerRate: 0.08,
    rows: [
      "SSSSSSSSSSSSS",
      "S...VVVVV...S",
      "S..VVVVVVV..S",
      "S...VVVVV...S",
      "SSSSSSSSSSSSS",
      ".....P.P.....",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 27,
    name: "Boss Plate II",
    ballSpeed: 1.58,
    paddle: 0.77,
    powerRate: 0.07,
    rows: [
      "SSSSSSSSSSSSS",
      "S..VVVVVVV..S",
      "S.VVVSSSVVV.S",
      "S..VVVVVVV..S",
      "SSSSSSSSSSSSS",
      "....E...E....",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 28,
    name: "Steel Funnel",
    ballSpeed: 1.6,
    paddle: 0.76,
    powerRate: 0.07,
    rows: [
      "SSSSS...SSSSS",
      "SNNNN...NNNNS",
      "S.HHHH.HHHH.S",
      "S..VVVVVVV..S",
      "S...EEEEE...S",
      "SSSSS...SSSSS",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 29,
    name: "Chaos Grid",
    ballSpeed: 1.62,
    paddle: 0.75,
    powerRate: 0.07,
    rows: [
      "MNHVESPNMHVSP",
      "H.S.E.N.P.S.E",
      "VNMHSPVNMHSPV",
      "E..P..E..P..E",
      "SSSSSSSSSSSSS",
      ".............",
      ".............",
      ".............",
      ".............",
      ".............",
    ],
  },
  {
    id: 30,
    name: "The Last Wall",
    ballSpeed: 1.65,
    paddle: 0.75,
    powerRate: 0.06,
    rows: [
      "SSSSSSSSSSSSS",
      "SVVVVVVVVVVVS",
      "SVVMMMEEEMMVS",
      "SVVHHHPPPHHVS",
      "SVVNNNNNNNVVS",
      "SVVHHHPPPHHVS",
      "SVVMMMEEEMMVS",
      "SVVVVVVVVVVVS",
      "SSSSSSSSSSSSS",
      ".....P...P...",
    ],
  },
];

/**
 * Get a level by ID (1-based).
 * Returns undefined if not found.
 */
export function getLevelById(id: number): LevelDef | undefined {
  return LEVEL_PACK.find((l) => l.id === id);
}

/** Total number of campaign levels. */
export const MAX_LEVEL = LEVEL_PACK.length;
