/** Cloud Functions entrypoint (imports/re-exports only). */
import { claimLevelReward, cleanupOldGameSessions, cleanupOldGames, cleanupResolvedInvites, cleanupStaleMatchmakingEntries, cleanupVacantGames, createGameFromInvite, expireGameInvites, expireMatchmakingEntries, makeMove, onGameCompletedCreateHistory, onGameHistoryCreatedUpdateLeaderboard, onGameResult, onUniversalInviteUpdate, processGameCompletion, processMatchmakingQueue, processRealtimeGameCompletion, reconcileActiveInvites, resignGame } from "./games";
import { createSessionV3, inviteToSessionV3, joinSessionV3, leaveSessionV3, resolveSessionV3, startSessionV3, watchdogSessionsV3 } from "./sessionsV3";
import { migrateGameInvites, migrateGameInvitesDryRun, rollbackGameInvitesMigration } from "./migrations/migrateGameInvites";
import { cleanupCallSignaling, getTurnCredentials, handleCallTimeouts, onCallCreated, onCallUpdated } from "./calls";
import { cleanupOldDeals, generateDailyDeals, generateWeeklyDeals, triggerDailyDeals } from "./dailyDeals";
import { expireGifts, getGiftHistory, openGift, sendGift } from "./gifting";
import { getPurchaseHistory, restorePurchases, validateReceipt } from "./iap";
import { grantItem, purchaseWithTokens } from "./shop";
import { grantCosmeticEntitlement, purchaseCosmeticWithTokens } from "./cosmeticEntitlements";
import { processSinglePlayerCompletion } from "./achievementsV2Evaluator";
import { adminApplyStrike, adminApplyWarning, adminLiftBan, adminResolveReport, adminSetAdminClaim, adminSetBan, initializeFirstAdmin } from "./admin";
import { claimTaskReward, initializeExistingWallets, onFriendAddedTaskProgress, onGamePlayedTaskProgress, onMessageSentTaskProgress, onStoryPostedTaskProgress, onStoryViewedTaskProgress, onUserCreated, recordDailyLogin, seedDailyTasks, seedMonthlyTasks } from "./economy";
import { onGameSessionCreated, onStreakAchievementCheck, weeklyLeaderboardReset } from "./leaderboards";
import { checkMessageRateLimit, onNewMessageEvent, onNewReport, sendFriendRequestWithRateLimit, updateExpiredBans } from "./moderation";
import { onNewGroupMessageV2, onNewMessage } from "./notifications";
import { cleanupExpiredPushTokens, cleanupExpiredSnaps, cleanupExpiredStories, cleanupOldScheduledMessages, streakReminder } from "./scheduled";
import { onScheduledMessageCreated, processScheduledMessages } from "./scheduledMessages";
import { onNewFriendRequest, onStoryViewed } from "./social";
import { onDeleteMessage, seedShopCatalog } from "./legacy";
import { cleanupStagingOrphans, mintChatMediaUrl } from "./chatMedia";
import { markInboxRead, onDMMessageInbox, onGroupMessageInbox } from "./inboxTriggers";
import { acceptMessageRequest, declineMessageRequest } from "./messageRequests";
import { getRateLimitStatus } from "./rateLimiter";
import { onChatSettingsChanged, onInboxSettingsChanged, publishDeliveryReceipt, publishReadReceipt, publishTypingIndicator } from "./privacyPublish";
import { incrementProfileViews } from "./profileViews";
export { getUserPushToken, isDmChatMuted, isGroupChatMuted, isValidString, isValidUid, sanitizeForLog, sendExpoPushNotification, } from "./utils";
export type { ExpoPushMessage } from "./utils";
export declare const sendMessageV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const editMessageV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const deleteMessageForAllV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const toggleReactionV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const fetchLinkPreview: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export { acceptMessageRequest, adminApplyStrike, adminApplyWarning, adminLiftBan, adminResolveReport, adminSetAdminClaim, adminSetBan, checkMessageRateLimit, claimLevelReward, claimTaskReward, cleanupCallSignaling, cleanupExpiredPushTokens, cleanupExpiredSnaps, cleanupExpiredStories, cleanupOldDeals, cleanupOldGameSessions, cleanupOldGames, cleanupOldScheduledMessages, cleanupResolvedInvites, cleanupStagingOrphans, cleanupStaleMatchmakingEntries, cleanupVacantGames, createGameFromInvite, createSessionV3, declineMessageRequest, expireGameInvites, expireGifts, expireMatchmakingEntries, generateDailyDeals, generateWeeklyDeals, getGiftHistory, getPurchaseHistory, getRateLimitStatus, getTurnCredentials, grantCosmeticEntitlement, grantItem, handleCallTimeouts, incrementProfileViews, initializeExistingWallets, initializeFirstAdmin, inviteToSessionV3, joinSessionV3, leaveSessionV3, makeMove, markInboxRead, migrateGameInvites, migrateGameInvitesDryRun, mintChatMediaUrl, onCallCreated, onCallUpdated, onDMMessageInbox, onDeleteMessage, onFriendAddedTaskProgress, onGameCompletedCreateHistory, onGameHistoryCreatedUpdateLeaderboard, onGamePlayedTaskProgress, onGameResult, onGameSessionCreated, onGroupMessageInbox, onMessageSentTaskProgress, onNewFriendRequest, onNewGroupMessageV2, onNewMessage, onNewMessageEvent, onNewReport, onScheduledMessageCreated, onStoryPostedTaskProgress, onStoryViewed, onStoryViewedTaskProgress, onStreakAchievementCheck, onUniversalInviteUpdate, onUserCreated, openGift, processGameCompletion, processMatchmakingQueue, processRealtimeGameCompletion, processScheduledMessages, processSinglePlayerCompletion, publishDeliveryReceipt, publishReadReceipt, publishTypingIndicator, purchaseCosmeticWithTokens, purchaseWithTokens, reconcileActiveInvites, recordDailyLogin, resignGame, resolveSessionV3, restorePurchases, rollbackGameInvitesMigration, seedDailyTasks, seedMonthlyTasks, seedShopCatalog, sendFriendRequestWithRateLimit, sendGift, startSessionV3, streakReminder, triggerDailyDeals, updateExpiredBans, validateReceipt, watchdogSessionsV3, weeklyLeaderboardReset, };
export declare const verifyIAPPurchase: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export { onChatSettingsChanged, onInboxSettingsChanged };
