/** Cloud Functions entrypoint (imports/re-exports only). */
import { cleanupCallSignaling, getTurnCredentials, handleCallTimeouts, onCallCreated, onCallUpdated } from "./calls";
import { cleanupOldDeals, generateDailyDeals, generateWeeklyDeals, triggerDailyDeals } from "./dailyDeals";
import { expireGifts, getGiftHistory, openGift, sendGift } from "./gifting";
import { getPurchaseHistory, restorePurchases, validateReceipt } from "./iap";
import { grantItem, purchaseWithTokens } from "./shop";
import { grantCosmeticEntitlement, purchaseCosmeticWithTokens } from "./cosmeticEntitlements";
import { adminApplyStrike, adminApplyWarning, adminLiftBan, adminResolveReport, adminSetAdminClaim, adminSetBan, initializeFirstAdmin } from "./admin";
import { claimTaskReward, initializeExistingWallets, onFriendAddedTaskProgress, onMessageSentTaskProgress, onStoryPostedTaskProgress, onStoryViewedTaskProgress, onUserCreated, recordDailyLogin, seedDailyTasks, seedMonthlyTasks } from "./economy";
import { checkMessageRateLimit, onNewMessageEvent, onNewReport, sendFriendRequestWithRateLimit, updateExpiredBans } from "./moderation";
import { onNewGroupMessageV2, onNewMessage } from "./notifications";
import { cleanupExpiredPushTokens, cleanupExpiredSnaps, cleanupExpiredStories, cleanupOldScheduledMessages, streakReminder } from "./scheduled";
import { onScheduledMessageCreated, processScheduledMessages } from "./scheduledMessages";
import { onNewFriendRequest, onStoryViewed } from "./social";
import { onDeleteMessage, seedShopCatalog } from "./legacy";
import { cleanupStagingOrphans, mintChatMediaUrl } from "./chatMedia";
import { markInboxRead, onDMMessageInbox, onGroupMessageInbox } from "./inboxTriggers";
import { acceptMessageRequest, declineMessageRequest } from "./messageRequests";
import { getRateLimitStatus } from "./rateLimiter";
import { onChatSettingsChanged, onInboxSettingsChanged, publishDeliveryReceipt, publishReadReceipt, publishTypingIndicator } from "./privacyPublish";
import { incrementProfileViews } from "./profileViews";
export { getUserPushToken, isDmChatMuted, isGroupChatMuted, isValidString, isValidUid, sanitizeForLog, sendExpoPushNotification, } from "./utils";
export type { ExpoPushMessage } from "./utils";
export declare const sendMessageV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const editMessageV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const deleteMessageForAllV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const toggleReactionV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const fetchLinkPreview: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export { acceptMessageRequest, adminApplyStrike, adminApplyWarning, adminLiftBan, adminResolveReport, adminSetAdminClaim, adminSetBan, checkMessageRateLimit, claimTaskReward, cleanupCallSignaling, cleanupExpiredPushTokens, cleanupExpiredSnaps, cleanupExpiredStories, cleanupOldDeals, cleanupOldScheduledMessages, cleanupStagingOrphans, declineMessageRequest, expireGifts, generateDailyDeals, generateWeeklyDeals, getGiftHistory, getPurchaseHistory, getRateLimitStatus, getTurnCredentials, grantCosmeticEntitlement, grantItem, handleCallTimeouts, incrementProfileViews, initializeExistingWallets, initializeFirstAdmin, markInboxRead, mintChatMediaUrl, onCallCreated, onCallUpdated, onDMMessageInbox, onDeleteMessage, onFriendAddedTaskProgress, onGroupMessageInbox, onMessageSentTaskProgress, onNewFriendRequest, onNewGroupMessageV2, onNewMessage, onNewMessageEvent, onNewReport, onScheduledMessageCreated, onStoryPostedTaskProgress, onStoryViewed, onStoryViewedTaskProgress, onUserCreated, openGift, processScheduledMessages, publishDeliveryReceipt, publishReadReceipt, publishTypingIndicator, purchaseCosmeticWithTokens, purchaseWithTokens, recordDailyLogin, restorePurchases, seedDailyTasks, seedMonthlyTasks, seedShopCatalog, sendFriendRequestWithRateLimit, sendGift, streakReminder, triggerDailyDeals, updateExpiredBans, validateReceipt, };
export declare const verifyIAPPurchase: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export { onChatSettingsChanged, onInboxSettingsChanged };
