/** Cloud Functions entrypoint (imports/re-exports only). */
import { cleanupOldGameSessions, cleanupOldGames, cleanupResolvedInvites, cleanupStaleMatchmakingEntries, createGameFromInvite, expireGameInvites, expireMatchmakingEntries, makeMove, onGameCompletedCreateHistory, onGameHistoryCreatedUpdateLeaderboard, onUniversalInviteUpdate, processGameCompletion, processMatchmakingQueue, resignGame } from "./games";
import { migrateGameInvites, migrateGameInvitesDryRun, rollbackGameInvitesMigration } from "./migrations/migrateGameInvites";
import { grantItem, purchaseWithTokens } from "./shop";
import { getPurchaseHistory, restorePurchases, validateReceipt } from "./iap";
import { expireGifts, getGiftHistory, openGift, sendGift } from "./gifting";
import { cleanupOldDeals, generateDailyDeals, generateWeeklyDeals, triggerDailyDeals } from "./dailyDeals";
import { cleanupCallSignaling, getTurnCredentials, handleCallTimeouts, onCallCreated, onCallUpdated } from "./calls";
import { onNewGroupMessageV2, onNewMessage } from "./notifications";
import { onNewFriendRequest, onStoryViewed } from "./social";
import { cleanupExpiredPushTokens, cleanupExpiredSnaps, cleanupExpiredStories, cleanupOldScheduledMessages, streakReminder } from "./scheduled";
import { onScheduledMessageCreated, processScheduledMessages } from "./scheduledMessages";
import { onGameSessionCreated, onStreakAchievementCheck, weeklyLeaderboardReset } from "./leaderboards";
import { claimTaskReward, initializeExistingWallets, onFriendAddedTaskProgress, onGamePlayedTaskProgress, onMessageSentTaskProgress, onStoryPostedTaskProgress, onStoryViewedTaskProgress, onUserCreated, recordDailyLogin, seedDailyTasks } from "./economy";
import { adminApplyStrike, adminApplyWarning, adminLiftBan, adminResolveReport, adminSetAdminClaim, adminSetBan, initializeFirstAdmin } from "./admin";
import { checkMessageRateLimit, onNewMessageEvent, onNewReport, sendFriendRequestWithRateLimit, updateExpiredBans } from "./moderation";
import { onDeleteMessage, seedShopCatalog } from "./legacy";
export { getUserPushToken, isDmChatMuted, isGroupChatMuted, isValidString, isValidUid, sanitizeForLog, sendExpoPushNotification, } from "./utils";
export type { ExpoPushMessage } from "./utils";
export declare const sendMessageV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const editMessageV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const deleteMessageForAllV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const toggleReactionV2: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export declare const fetchLinkPreview: import("firebase-functions/v1").HttpsFunction & import("firebase-functions/v1").Runnable<any>;
export { adminApplyStrike, adminApplyWarning, adminLiftBan, adminResolveReport, adminSetAdminClaim, adminSetBan, checkMessageRateLimit, claimTaskReward, cleanupCallSignaling, cleanupExpiredPushTokens, cleanupExpiredSnaps, cleanupExpiredStories, cleanupOldDeals, cleanupOldGameSessions, cleanupOldGames, cleanupOldScheduledMessages, cleanupResolvedInvites, cleanupStaleMatchmakingEntries, createGameFromInvite, expireGameInvites, expireGifts, expireMatchmakingEntries, generateDailyDeals, generateWeeklyDeals, getGiftHistory, getPurchaseHistory, getTurnCredentials, grantItem, handleCallTimeouts, initializeExistingWallets, initializeFirstAdmin, makeMove, migrateGameInvites, migrateGameInvitesDryRun, onCallCreated, onCallUpdated, onDeleteMessage, onFriendAddedTaskProgress, onGameCompletedCreateHistory, onGameHistoryCreatedUpdateLeaderboard, onGamePlayedTaskProgress, onGameSessionCreated, onMessageSentTaskProgress, onNewFriendRequest, onNewGroupMessageV2, onNewMessage, onNewMessageEvent, onNewReport, onScheduledMessageCreated, onStoryPostedTaskProgress, onStoryViewed, onStoryViewedTaskProgress, onStreakAchievementCheck, onUniversalInviteUpdate, onUserCreated, openGift, processGameCompletion, processMatchmakingQueue, processScheduledMessages, purchaseWithTokens, recordDailyLogin, resignGame, restorePurchases, rollbackGameInvitesMigration, seedDailyTasks, seedShopCatalog, sendFriendRequestWithRateLimit, sendGift, streakReminder, triggerDailyDeals, updateExpiredBans, validateReceipt, weeklyLeaderboardReset, };
